#!/usr/bin/env python3
"""
convert_kernel_to_tflite.py — Convert trained Kernel MLP to INT8 TFLite
and generate a C header for ESP32-S3.

Usage:
    python convert_kernel_to_tflite.py --model kernel_model/kernel_classifier.keras
"""

import argparse
import json
import os

import numpy as np
import pandas as pd
import tensorflow as tf

KERNEL_STATES = [
    "STABLE", "DOOR_OPEN", "RECOVERING", "DEFROST",
    "DRIFT_WARM", "DRIFT_COLD", "EXCURSION", "COMP_STRESS", "FAULT"
]

FEATURE_NAMES = [
    "temp_mean", "temp_delta", "temp_rate", "temp_volatility", "temp_ambient_gap",
    "power_mean", "power_delta", "freq_mean", "freq_stability", "cop_mean",
    "cop_trend", "temp_rate_vs_power", "recovery_efficiency", "door_state", "door_duration"
]


def tflite_to_c_header(tflite_path, header_path, var_name="kernel_model_data"):
    """Convert .tflite to C header (reuses pattern from existing converter)."""
    with open(tflite_path, "rb") as f:
        data = f.read()

    lines = []
    lines.append(f"const unsigned char __attribute__((aligned(8))) {var_name}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_vals},")
    lines.append("};")
    lines.append(f"const unsigned int {var_name}_len = {len(data)};")
    c_code = "\n".join(lines)

    header_content = (
        "/*\n"
        " * kernel_model_data.h — Auto-generated TFLite Kernel classifier as C byte array\n"
        " *\n"
        " * Generated by convert_kernel_to_tflite.py\n"
        " * Model: INT8-quantized MLP for 9-state cold chain classification\n"
        " */\n\n"
        "#ifndef KERNEL_MODEL_DATA_H\n"
        "#define KERNEL_MODEL_DATA_H\n\n"
        f"{c_code}\n\n"
        "#endif  // KERNEL_MODEL_DATA_H\n"
    )

    with open(header_path, "w") as f:
        f.write(header_content)
    print(f"C header saved to {header_path}")


def main():
    parser = argparse.ArgumentParser(description="Convert Kernel MLP to INT8 TFLite")
    parser.add_argument(
        "--model", type=str,
        default="kernel_model/kernel_classifier.keras",
        help="Path to trained Keras model"
    )
    parser.add_argument(
        "--params", type=str,
        default="kernel_model/kernel_deploy_params.json",
        help="Path to deploy params"
    )
    parser.add_argument(
        "--data", type=str,
        default="kernel_model/kernel_training_data.csv",
        help="Training data for representative dataset"
    )
    parser.add_argument(
        "--output-dir", type=str,
        default="kernel_model",
        help="Output directory"
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # Load deploy params
    with open(args.params) as f:
        deploy_params = json.load(f)

    # Load representative data (500 stratified samples)
    df = pd.read_csv(args.data)
    fmin = np.array(deploy_params["feature_min"], dtype=np.float32)
    fmax = np.array(deploy_params["feature_max"], dtype=np.float32)

    rng = np.random.default_rng(args.seed)
    label_to_idx = {s: i for i, s in enumerate(KERNEL_STATES)}

    # Stratified sampling: ~500 total
    rep_samples = []
    for state in KERNEL_STATES:
        state_df = df[df["label"] == state]
        n_take = min(60, len(state_df))
        indices = rng.choice(len(state_df), size=n_take, replace=False)
        samples = state_df[FEATURE_NAMES].values[indices].astype(np.float32)
        # Normalize
        samples_norm = (samples - fmin) / (fmax - fmin + 1e-8)
        rep_samples.append(samples_norm)

    rep_data = np.concatenate(rep_samples, axis=0)
    print(f"Representative dataset: {len(rep_data)} samples")

    # Load float model
    model = tf.keras.models.load_model(args.model)

    # Convert to TFLite with INT8 quantization
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    def representative_dataset():
        for i in range(len(rep_data)):
            yield [rep_data[i:i+1].astype(np.float32)]

    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    tflite_path = os.path.join(args.output_dir, "kernel_classifier.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"TFLite model: {tflite_path} ({size_kb:.1f} KB)")

    if size_kb > 50:
        print(f"WARNING: Model size {size_kb:.1f}KB exceeds 50KB target")
    else:
        print(f"PASS: Model size {size_kb:.1f}KB within 50KB target")

    # Generate C header
    header_path = os.path.join(args.output_dir, "kernel_model_data.h")
    tflite_to_c_header(tflite_path, header_path)

    # Validate INT8 accuracy
    print("\nValidating INT8 accuracy...")
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    input_scale = input_details[0]["quantization_parameters"]["scales"][0]
    input_zero = input_details[0]["quantization_parameters"]["zero_points"][0]
    output_scale = output_details[0]["quantization_parameters"]["scales"][0]
    output_zero = output_details[0]["quantization_parameters"]["zero_points"][0]

    # Test on 200 samples
    test_samples = rep_data[:200]
    X_norm_full = test_samples

    # Float model predictions
    float_preds = model.predict(X_norm_full, verbose=0).argmax(axis=1)

    # INT8 predictions
    int8_preds = []
    for i in range(len(X_norm_full)):
        sample = X_norm_full[i:i+1]
        quant_input = np.round(sample / input_scale + input_zero).astype(np.int8)
        interpreter.set_tensor(input_details[0]["index"], quant_input)
        interpreter.invoke()
        output = interpreter.get_tensor(output_details[0]["index"])
        int8_preds.append(output[0].argmax())

    int8_preds = np.array(int8_preds)
    match_rate = (float_preds == int8_preds).mean() * 100
    print(f"  Float vs INT8 agreement: {match_rate:.1f}%")

    # Per-class check
    for state in KERNEL_STATES:
        idx = label_to_idx[state]
        mask = float_preds == idx
        if mask.sum() > 0:
            cls_match = (float_preds[mask] == int8_preds[mask]).mean() * 100
            print(f"  {state}: {cls_match:.1f}% agreement ({mask.sum()} samples)")

    if match_rate >= 98:
        print("\nPASS: INT8 accuracy within 2% of float model")
    else:
        print(f"\nWARNING: INT8 accuracy drop of {100-match_rate:.1f}%")

    print(f"\nOutputs:\n  {tflite_path}\n  {header_path}")


if __name__ == "__main__":
    main()
