#!/usr/bin/env python3
"""
convert_to_tflite.py — Quantize trained autoencoder to INT8 TFLite
and generate a C header for embedding in ESP32-S3 firmware.

Usage:
    python convert_to_tflite.py \
        --model trained_model/autoencoder.keras \
        --data baseline_data.csv \
        --output ../TinyML_ESP32S3/model_data.h

This produces:
  1. cold_storage_anomaly.tflite — INT8 quantized TFLite model
  2. model_data.h — C byte array header for Arduino sketch
"""

import argparse
import json
import os
import sys

import numpy as np
import pandas as pd
import tensorflow as tf

WINDOW_SIZE = 50
NUM_CHANNELS = 4


def load_representative_data(csv_path: str, norm_params: dict, n_samples: int = 200):
    """Load and preprocess data for representative dataset calibration."""
    df = pd.read_csv(csv_path)
    cols = ["accel_x", "accel_y", "accel_z", "temperature"]
    data = df[cols].values.astype(np.float32)

    ch_min = np.array(norm_params["ch_min"], dtype=np.float32)
    ch_max = np.array(norm_params["ch_max"], dtype=np.float32)
    data_norm = (data - ch_min) / (ch_max - ch_min + 1e-8)

    stride = WINDOW_SIZE // 2
    windows = []
    for i in range(0, len(data_norm) - WINDOW_SIZE + 1, stride):
        windows.append(data_norm[i : i + WINDOW_SIZE])
        if len(windows) >= n_samples:
            break

    return np.array(windows, dtype=np.float32)


def convert_to_tflite(model_path: str, representative_data: np.ndarray, output_path: str):
    """Convert Keras model to INT8 quantized TFLite."""
    model = tf.keras.models.load_model(model_path)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    def representative_dataset():
        for i in range(len(representative_data)):
            yield [representative_data[i : i + 1]]

    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    with open(output_path, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"TFLite model saved to {output_path} ({size_kb:.1f} KB)")
    return tflite_model


def tflite_to_c_header(tflite_path: str, header_path: str, var_name: str = "model_data"):
    """Convert .tflite binary to a C header file using xxd."""
    # Generate C array directly in Python (avoids xxd path-mangling issues)
    with open(tflite_path, "rb") as f:
        data = f.read()

    lines = []
    lines.append(f"const unsigned char __attribute__((aligned(8))) {var_name}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_vals},")
    lines.append("};")
    lines.append(f"const unsigned int {var_name}_len = {len(data)};")
    c_code = "\n".join(lines)

    # Wrap in header guard
    header_content = (
        "/*\n"
        " * model_data.h — Auto-generated TFLite model as C byte array\n"
        " *\n"
        " * Generated by convert_to_tflite.py\n"
        " * Model: INT8-quantized Conv1D autoencoder for cold storage anomaly detection\n"
        " */\n\n"
        "#ifndef MODEL_DATA_H\n"
        "#define MODEL_DATA_H\n\n"
        f"{c_code}\n\n"
        "#endif  // MODEL_DATA_H\n"
    )

    with open(header_path, "w") as f:
        f.write(header_content)

    print(f"C header saved to {header_path}")


def main():
    parser = argparse.ArgumentParser(description="Convert autoencoder to INT8 TFLite + C header")
    parser.add_argument("--model", type=str, default="trained_model/autoencoder.keras",
                        help="Path to trained Keras model")
    parser.add_argument("--data", type=str, required=True,
                        help="Path to baseline CSV for representative dataset calibration")
    parser.add_argument("--params", type=str, default="trained_model/deploy_params.json",
                        help="Path to deploy_params.json from training")
    parser.add_argument("--output", type=str, default="../TinyML_ESP32S3/model_data.h",
                        help="Output path for C header")
    args = parser.parse_args()

    # Load normalization params
    with open(args.params, "r") as f:
        deploy_params = json.load(f)

    # Load representative data
    print("Loading representative data for quantization calibration...")
    rep_data = load_representative_data(args.data, deploy_params["norm"])
    print(f"Using {len(rep_data)} calibration samples")

    # Convert to TFLite
    tflite_path = os.path.join(os.path.dirname(args.model), "cold_storage_anomaly.tflite")
    convert_to_tflite(args.model, rep_data, tflite_path)

    # Generate C header
    tflite_to_c_header(tflite_path, args.output)

    print(f"\nDone! Copy {args.output} into your Arduino sketch folder.")
    print("Update the normalization params and threshold in TinyML_ESP32S3.ino:")
    print(f"  ch_min = {deploy_params['norm']['ch_min']}")
    print(f"  ch_max = {deploy_params['norm']['ch_max']}")
    print(f"  ANOMALY_THRESHOLD = {deploy_params['anomaly_threshold']:.6f}")


if __name__ == "__main__":
    main()
